### ISSUE TITLE
/dashboard loses session too fast

### ISSUE THREAD

**Issue by aekeus** [brave/vault-analytics#1]
If leave the tab open then periodically click on User(Aggregated) it will stop responding and not show the stats. When it's in this state, if I reload it takes me back to the login screen.

Maybe we just need to set a persistent login cookie or increase the session timeout length by a ton.

**Comment by aekeus** [comment]
I think the issue is that it is running on a hobby Heroku dyno that powers down when not used. @bbondy 

The timeout value is set much higher than what we are experiencing.

**Comment by bbondy** [comment]
fixed?

**Comment by aekeus** [comment]
We need to upgrade the dyno if we want the sessions to last longer than their power down time.

**Comment by bbondy** [comment]
gotcha ok.
