### ISSUE TITLE
Selecting iOS for analytics makes all time graph show too many data points

### ISSUE THREAD

**Issue by bbondy** [brave/vault-analytics#11]
Viewing "All time", there are too many 0 entries for a time period we didn't track for Android and iOS. It makes the graph show a ton of data points and the graph is hard to read.  Could we strip those leading 0 days out?

**Comment by bbondy** [comment]
Also happens for Android.

**Comment by aekeus** [comment]
Fixed with commit 08469df38f45d4e66deca1743b8552488a143404
