### ISSUE TITLE
vulnerable dependencies

### ISSUE THREAD

**Issue by diracdeltas** [brave/vault-analytics#27]
github shows a warning for vulnerable deps in this repo:
![screen shot 2018-02-13 at 12 08 30 pm](https://user-images.githubusercontent.com/549654/36171229-ae66c29a-10b6-11e8-9a24-b808d5ba6cd7.png)

**Comment by diracdeltas** [comment]
@aekeus any update on this? still showing the warning in github

**Comment by aekeus** [comment]
No update. I will try and get to it this week.
