### ISSUE TITLE
Version charts issue with legend

### ISSUE THREAD

**Issue by bbondy** [brave/vault-analytics#5]
Version charts look great but when I hover over I see the values but not the version that line corresponds to.  I can't match up the values to the versions without trying to plot the raw data points.

<img width="166" alt="screenshot 2016-02-03 09 22 34" src="https://cloud.githubusercontent.com/assets/831718/12784886/bd2db1c8-ca57-11e5-8290-b7920c412d9a.png">

**Comment by aekeus** [comment]
Legend added for line graphs using Chart.js generateLegend() method
