### ISSUE TITLE
Mouse over combines all graphs

### ISSUE THREAD

**Issue by bbondy** [brave/vault-analytics#7]
i) Select crash reports
ii) Hover over the graph and notice that it selects dots from the other graphs.  I think the other graphs need a display: none or something like that.

**Comment by aekeus** [comment]
I saw that. I need to re-create the canvas element whenever the dataset changes. Otherwise Chart.js gets confused.

**Comment by aekeus** [comment]
Fixed by commit f0719e5a27803948a27e96807ac35abbc197a054
